import os

MODEL_NAME = "claude-sonnet-4-5-20250929"
PHASE_A_MODEL = "claude-sonnet-4-5-20250929"
MAX_CONVERSATION_TURNS = 50  # Safety limit

# --- RAG / Embedding Settings ---
VOYAGE_API_KEY = os.getenv("VOYAGE_API_KEY", "")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "voyage-3.5-lite")
EMBEDDING_DIMENSIONS = 512

LEAF_CHUNK_MIN_TOKENS = 100
LEAF_CHUNK_MAX_TOKENS = 500
PARENT_CHUNK_MAX_TOKENS = 2000

MAX_DOCUMENT_RESULTS = 4
MAX_CONVERSATION_RESULTS = 3
ALWAYS_ON_TURN_WINDOW = 3

TURN_SUMMARY_MODEL = os.getenv("TURN_SUMMARY_MODEL", "claude-haiku-4-5-20251001")
